---
tandoor_enabled: false
tandoor_available_externally: false

tandoor_container_name: tandoor
tandoor_container_store: vabene1111
tandoor_config_directory: "{{ docker_app_data }}/tandoor"
tandoor_version: 1.0.4.1
tandoor_port_http: 8142
tandoor_port_https: 8143
tandoor_hostname: tandoor
tandoor_user_id: "0"
tandoor_group_id: "0"
tandoor_memory: 1g


tandoor_db_container_version: 11-alpine
tandoor_nginx_version: mainline-alpine
